export const SET_DATE_INFO = "SET_DATE_INFO";
export const SET_TIME_INFO = "SET_TIME_INFO";
export const SET_TIMEJONE_INFO = "SET_TIMEJONE_INFO";
export const SET_CONFIRM_STATUS = "SET_CONFIRM_STATUS";
